# shamelessly cribbed from https://github.com/pydata/xarray/blob/master/.github/workflows/ci.yaml
# and from https://github.com/conda-incubator/setup-miniconda
name: Build and test climlab (linux / macos)

on: push

jobs:
  build-and-test:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        include:
          - os: ubuntu-latest
            environment-file: ci/requirements-linux.yml
          - os: macos-latest
            environment-file: ci/requirements-macos.yml
          - os: windows-latest
            environment-file: ci/requirements-windows.yml

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.environment-file }}
          miniconda-version: latest
      - name: Build and install climlab
        run: |
          python -m pip install --no-deps -e .
      - name: Import climlab
        run: |
          python -c "import climlab"
      - name: Run tests
        run: |
          pytest -v --pyargs climlab.tests
        #   when we're ready to use codecov again
        # run: |
        #   pytest -v --pyargs climlab.tests --cov=climlab --cov-config .coveragerc --cov-report term-missing -v
        #   codecov
