# shamelessly cribbed from https://github.com/pydata/xarray/blob/master/.github/workflows/ci.yaml
# and from https://github.com/conda-incubator/setup-miniconda
name: Build and test climlab

on: push

jobs:
  build-linux:
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest",]
        python-version: ["3.7",]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test_env
          environment-file: ci/requirements-py37-linux.yml
          miniforge-version: latest
      - name: Version info  #just to figure out what's going on
        run: |
          conda info -a
          conda list
      - name: Build and install climlab
        run: |
          python -m pip install --no-deps -e .
      - name: Import climlab
        run: |
          python -c "import climlab"
      - name: Run tests
        run: |
          python -m pytest -n 4 \
             --cov=climlab \
             --cov-report=xml
